---
apiVersion: v1
kind: Service
# Who am I ? I am Saint Nectaire
metadata:
  name: whoami
  labels:
    app: whoami
    # eks.amazonaws.com/fargate-profile: giofargateprofile
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: whoami
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
        # eks.amazonaws.com/fargate-profile: giofargateprofile
        # don't EVER label [kind: Deployment]s : will trigger a Fargate Profile error
        # Same with [kind: ReplicaSet]s or any other [kind], but [kind: Service]s I believe : will trigger a Fargate Profile error
        # Only label [kind: Service]s
    spec:
      containers:
        - name: whoami
          image: containous/whoami
          ports:
            - name: web
            # - name: web-nectaire # à testr pour tester le lien Ingress Route / canal websecure...
              containerPort: 80
